### ISSUE TITLE
"File does not exist" with relative path

### ISSUE THREAD

**Issue by Tartopohm** [BentonEdmondson/knock#37]
I just downloaded the last release (knock-1.1.0-alpha-x86_64-linux; latest kernel on an Arch install). Relative paths do not work, even in the same directory as the executable. No problem with absolute paths.

**Comment by MeatH00k** [comment]
+1
Manjaro (Arch)
Absolute paths don't even work for me.

Error: Invalid value for 'PATH': File '...' does not exist.

**Comment by 0xdeadc0de** [comment]
I used ~/Downloads/file.acsm and it worked

**Comment by alexhernandezgarcia** [comment]
Same. Weirdly enough it doesn't work with relative path, it does with absolute path.

**Comment by BentonEdmondson** [comment]
Alright. This is weird because my understanding was that the shell expands relative paths before even sending them to the executable, but I guess not? Relative paths on `1.1.0-alpha` for sure works on my machine (unlike `1.0.0-alpha`), but I'll look into this when I get a chance. I do also want to eventually get globs working. E.g. `knock ./*.acsm` to run a whole file.

**Comment by BentonEdmondson** [comment]
Fixed in release `1.2.0`
