### ISSUE TITLE
error ../run: 1: ./nix/store/ml4m2016xm278m8h4w1x3gaayq9kh3p2-startup: not found

### ISSUE THREAD

**Issue by piscvau** [BentonEdmondson/knock#54]
On xubuntu 20.04 reading a .acsm file coming from kobo I get the following erro :

+1: ../run: 1: ./nix/store/ml4m2016xm278m8h4w1x3gaayq9kh3p2-startup: not found

**Comment by raphink** [comment]
Same here on Ubuntu 22.04

**Comment by cjmabry** [comment]
Per the README you can fix by enabling user namespaces, although it should be noted there [might be security ramifications to this](https://security.stackexchange.com/a/209533):

`echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf
sudo reboot`

**Comment by piscvau** [comment]
I have enabled the user namespaces before running the program which produced the above mentioned error. 
This was also true for Tomasa88 in this exchange https://superuser.com/questions/1027608/how-to-read-an-acsm-file-on-linux. Third comment from December28 2021.

**Comment by tsukasagenesis** [comment]
Same issue here, the version [0.1.0-alpha](https://github.com/BentonEdmondson/knock/releases/tag/0.1.0-alpha) work but the last version give me error :
/tmp/tmpx-6b7076ef32134332/dat/../run: line 1: ./nix/store/ml4m2016xm278m8h4w1x3gaayq9kh3p2-startup: No such file or directory

I do have kernel.unprivileged_userns_clone=1

manjaro kde

**Comment by BentonEdmondson** [comment]
@piscvau, @raphink, @tsukasagenesis try release `1.2.0` and tell me what happens. the user namespaces stuff is no longer required

**Comment by tsukasagenesis** [comment]
Sorry for the late answer, the issue is indeed gone, but it doesn't work at all anymore :
downloading the file from Adobe...
error:
Exception code : 0x1003
Message        : E_LIC_ALREADY_FULFILLED_BY_ANOTHER_USER http://acs4.kobo.com/fulfillment/Fulfill xxxxxxxxxxxxxxxxxx urn:uuid:xxxxxxxxxxxxxxxxx


I just try again right now with version 0.1.0 and it still work (but the extracting is not correct, but that's another matter).

**Comment by BentonEdmondson** [comment]
`E_LIC_ALREADY_FULFILLED_BY_ANOTHER_USER` means the book was converted by another user (i.e. another Adobe account). Now we're doing anonymous conversions so each ACSM file can only be converted once. If you convert it and don't have access to the corresponding EPUB/PDF anymore for whatever reason, readownload a fresh ACSM file from wherever you originally got it and redo the conversion. This issue is resolved so I'll close. I'm thinking I'll make the common errors such as this one nicer-reading.
